### ISSUE TITLE
no tests

### ISSUE THREAD

**Issue by sdwvit** [ibessonov/java-tailrec-agent#1]
Hi, the idea is cool. But could you try adding some tests to see if it works?

feel free to close this issue if it's impossible at the moment

**Comment by ibessonov** [comment]
Hi, there are tests, but not in "test" scope. You could see "Main.java", it contains some good and some bad ones. It was the only way for me to ensure that the agent actually works :)
I will probably add more cases, thank you for the message!

**Comment by ibessonov** [comment]
Done!
